version: "3"

services:
  status-lights:
    container_name: status-lights
    privileged: true
    image: ghsapp/status-lights
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ~/secrets:/statusLights/secrets
