version: "3"

services:
  rpi-status:
    container_name: rpi-status
    privileged: true
    image: mattgleich/rpi-status
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
